---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    orientation: rows
    vertical_layout: fill
runtime: shiny

---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(shiny)
library(dplyr)
library(tidyr)
library(formattable)
library(lubridate)
sales <- read.csv("sales.csv")
product <- read.csv("product.csv")


dak <- merge(sales, product, by = "product_id")



dak2 <- dak %>% group_by(transaction_date, product_category) %>% summarise(sumk = sum(unit_price*quantity))
 #dak2 <- dak2 %>% dak2$changeround((((dak2$sumk)-lag(dak2$sumk))/lag(dak2$sumk)*100),2)

dak3 <- dak %>% group_by(product_category) %>% summarise(sum_by_category = sum(unit_price*quantity)) %>% arrange(desc(sum_by_category))


#sort 
dak3$product_category <- factor(dak3$product_category, levels = c(as.character(dak3$product_category)))

product_cat = dak %>% distinct(product_category) %>% pull()


#
#dak2$transaction_date <- as.Date(dak2$transaction_date)


```




```{css, echo = FALSE}

.chart-title , #section-column{
  background-color: #d3d3d3;
  color: white;
  font-family: "Lucida Console", "Courier New", monospace;
   font-size: 15px;

}



#section-column-1 {
 height: 80px;
 color: #d3d3d3;
   font-family: "Lucida Console", "Courier New", monospace;
    font-size: 12px;
 
 
}

.value-output {
  font-size: 22px;
  position: relative;
  top: -10px;
  border-radius: 50%;
  
  
}

.caption {
  font-size: 12px;
  position:relative;
  bottom: 20px; 
}

#section-column-3 {
 max-height: 150px;
 height: 100%;
 font-family: "Lucida Console", "Courier New", monospace;
    font-size: 10px;
   text-align: center;
   vertical-align: middle;
 
}

#section-column-2 {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: lightgray 5px center/3em no-repeat;
  border: 2px solid black;
  border-radius: 10px;
}

```



Column {.sidebar}
--------------------------------------------------------------------------

```{r}
selectInput("product_choice", label = h5("Select the Product"), 
            choices = product_cat, selected = product_cat[1])


#dateRangeInput("date_range", label = h5("Select the Date range:"),
#               start = min(dak2$transaction_date),
 #              end = max(dak2$transaction_date),
    #            min = min(dak2$transaction_date), 
    #               max = max(dak2$transaction_date),
     #           format = "mm/dd/yyyy",
     #          separator = "/")

```

Column 1
-----------------------------------------------------------------------

### Total Profit

```{r}
renderValueBox({
  total.orders  <- paste0(prettyNum(round(sum(dak$sales)), big.mark = ","), "$")
  valueBox(
    value = total.orders, color = "#36454f" 
    
  )
})

# "#08526b"
```

### Total Transactions 

```{r}
renderValueBox({
  total.transactions  <- prettyNum(length(unique(dak$transaction_id)), big.mark = ",")
  valueBox(
    value = total.transactions, color = "#536872"
  )
})

```

### Total Quantity Sold 

```{r}
renderValueBox({
  total.q  <- prettyNum(round(sum(dak$order)), big.mark = ",")
  valueBox(
    value = total.q, color = "#536878"
  )
})

```

### Total Customers 

```{r}
renderValueBox({
  total.customers  <- prettyNum(length(unique(dak$customer_id)), big.mark = ",")
  valueBox(
    value = total.customers, color = "	#708090"
  )
})

```

#renderValueBox({
#    valueBox( #     "55%",
#      HTML(paste("test_value that is super long like this",br(),"Estimated: 98%")),
#     icon = icon("credit-card")
#    )})
  


### Total Staff

```{r}
renderValueBox({
  total.staff  <- prettyNum(length(unique(dak$staff_id)), big.mark = ",")
  valueBox(
    value = total.staff, color = "#6e7f80"

  )
})

```


Column 2 
-----------------------------------------------------------------------

### Profit - Filter by Product                         

```{r}
renderPlotly({
  
 dak2 %>% filter(product_category %in% input$product_choice) %>%
plot_ly(x = ~ transaction_date, y = ~ sumk, type = 'scatter', mode = 'markers+lines',  line = list(color = "#57A0D3", width = 4), fill = 'tozeroy') %>%
  layout(title = "",
         xaxis = list(title = "" ,
                      zeroline = FALSE),
         yaxis = list(title = "" ,
                      zeroline = FALSE))




})
```



```{r}
#plot2
#dak3$product_category
plot_ly(
  data=dak3,
  x = ~product_category,
  y = ~sum_by_category,
  type = "bar", 
  marker = list(color = "#57A0D3",
                            line = list(color = "Carolina",
                                        width = 1.5),
                tickangle = 90)) %>%
  add_text(text = ~paste0( scales::percent(sum_by_category/sum(sum_by_category))), 
           textposition = "top", 
           textfont = list(size = 12, color = "#36454f")) %>%
   layout(xaxis = list(title = ""), yaxis = list(title = ""), showlegend = FALSE)



```



```{r}
renderFormattable({
  formattable(dak3)
  })

```




```{r}
renderFormattable({
  formattable(dak3)
  })

```



Column 3
-----------------------------------------------------------------------
 
### Top 10 - Profit by Staff

```{r}
renderFormattable({
  
  formattable(dak2 %>% filter(product_category %in% input$product_choice) %>% spread(transaction_date,  sumk), align = c("l",rep("r", NCOL(dak2) - 3)))

})

```
